In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=sns.load_dataset("iris")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split
X=df.drop("species",axis=1)
Y=df["species"]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,Y_train)

KNeighborsClassifier()

In [12]:
model.score(X_test,Y_test)

0.98

In [13]:
from sklearn.svm import SVC

In [17]:
model=SVC(gamma="auto",kernel="rbf",C=20)

In [19]:
model.fit(X_train,Y_train)

SVC(C=20, gamma='auto')

In [20]:
model.score(X_test,Y_test)

0.98

GRID SEARCH CV

In [21]:
from sklearn.model_selection import GridSearchCV

In [23]:
classifier=GridSearchCV((model),{
    'C':[1,10,20,30,40],
    'kernel':['linear','poly','rbf','sigmoid']
    } , cv=5,return_train_score=False)

In [24]:
classifier.fit(X,Y)

GridSearchCV(cv=5, estimator=SVC(C=20, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30, 40],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [26]:
classifier.cv_results_

{'mean_fit_time': array([0.003756  , 0.00636821, 0.00352783, 0.00220671, 0.00160341,
        0.00374475, 0.00158677, 0.00214076, 0.00150805, 0.00555348,
        0.00163951, 0.00215974, 0.00201912, 0.00617433, 0.00184002,
        0.00243907, 0.00199251, 0.0064528 , 0.0017314 , 0.00220728]),
 'std_fit_time': array([0.00187641, 0.00130746, 0.00144165, 0.00038727, 0.00050005,
        0.00134091, 0.00037575, 0.000572  , 0.00043034, 0.00508172,
        0.00063724, 0.00086638, 0.00024179, 0.00409917, 0.00077913,
        0.00101891, 0.00044847, 0.00408979, 0.0004204 , 0.0007624 ]),
 'mean_score_time': array([0.002636  , 0.00363832, 0.00205426, 0.00151968, 0.00112157,
        0.00122714, 0.00130925, 0.00130668, 0.00128527, 0.00114522,
        0.00110655, 0.00138812, 0.00252838, 0.00157137, 0.001232  ,
        0.00185533, 0.00160241, 0.0013289 , 0.0012835 , 0.00150251]),
 'std_score_time': array([0.0010305 , 0.00074208, 0.00065268, 0.00056459, 0.00025113,
        0.00035484, 0.00036878, 0.00045681, 0.0005659 , 0.00030103,
        0.0004678 , 0.00072876, 0.00055066, 0.00036884, 0.00035042,
        0.00080566, 0.0002377 , 0.00032059, 0.00030071, 0.0004951 ]),
 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10, 20, 20, 20, 20, 30, 30, 30,
                    30, 40, 40, 40, 40],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'sigmoid'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'poly'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'sigmoid'},
  {'C': 40, 'kernel': 'linear'},
  {'C': 40, 'kernel': 'poly'},
  {'C': 40, 'kernel': 'rbf'},
  {'C': 40, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.96666667, 1.        , 0.96666667, 0.33333333, 1.        ,
        1.        , 0.96666667, 0.33333333, 1.        , 0.96666667,
        0.96666667, 0.33333333, 1.        , 0.96666667, 0.96666667,
        0.33333333, 1.        , 0.96666667, 1.        , 0.33333333]),
 'split1_test_score': array([1.        , 1.        , 1.        , 0.1       , 1.        ,
        1.        , 1.        , 0.1       , 1.        , 0.96666667,
        1.        , 0.1       , 1.        , 0.96666667, 1.        ,
        0.1       , 1.        , 0.96666667, 0.96666667, 0.1       ]),
 'split2_test_score': array([0.96666667, 0.9       , 0.96666667, 0.        , 0.9       ,
        0.9       , 0.96666667, 0.        , 0.9       , 0.9       ,
        0.9       , 0.        , 0.9       , 0.9       , 0.9       ,
        0.        , 0.9       , 0.9       , 0.9       , 0.        ]),
 'split3_test_score': array([0.96666667, 0.93333333, 0.96666667, 0.03333333, 0.96666667,
        0.93333333, 0.96666667, 0.03333333, 0.93333333, 0.93333333,
        0.96666667, 0.03333333, 0.9       , 0.93333333, 0.93333333,
        0.03333333, 0.9       , 0.93333333, 0.93333333, 0.03333333]),
 'split4_test_score': array([1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
        1., 1., 0.]),
 'mean_test_score': array([0.98      , 0.96666667, 0.98      , 0.09333333, 0.97333333,
        0.96666667, 0.98      , 0.09333333, 0.96666667, 0.95333333,
        0.96666667, 0.09333333, 0.96      , 0.95333333, 0.96      ,
        0.09333333, 0.96      , 0.95333333, 0.96      , 0.09333333]),
 'std_test_score': array([0.01632993, 0.0421637 , 0.01632993, 0.12543258, 0.03887301,
        0.0421637 , 0.01632993, 0.12543258, 0.0421637 , 0.03399346,
        0.03651484, 0.12543258, 0.04898979, 0.03399346, 0.03887301,
        0.12543258, 0.04898979, 0.03399346, 0.03887301, 0.12543258]),
 'rank_test_score': array([ 1,  6,  1, 16,  4,  6,  1, 16,  6, 13,  5, 16,  9, 13,  9, 16,  9,
        13,  9, 16], dtype=int32)}

In [27]:
result=pd.DataFrame(classifier.cv_results_)

In [28]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003756,0.001876,0.002636,0.001031,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.006368,0.001307,0.003638,0.000742,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
2,0.003528,0.001442,0.002054,0.000653,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002207,0.000387,0.001520,0.000565,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,16
4,0.001603,0.000500,0.001122,0.000251,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
5,0.003745,0.001341,0.001227,0.000355,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001587,0.000376,0.001309,0.000369,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.002141,0.000572,0.001307,0.000457,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,16
8,0.001508,0.000430,0.001285,0.000566,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
9,0.005553,0.005082,0.001145,0.000301,20,poly,"{'C': 20, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,13
10,0.001640,0.000637,0.001107,0.000468,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
11,0.002160,0.000866,0.001388,0.000729,20,sigmoid,"{'C': 20, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,16
12,0.002019,0.000242,0.002528,0.000551,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
13,0.006174,0.004099,0.001571,0.000369,30,poly,"{'C': 30, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,13
14,0.001840,0.000779,0.001232,0.000350,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9
15,0.002439,0.001019,0.001855,0.000806,30,sigmoid,"{'C': 30, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,16
16,0.001993,0.000448,0.001602,0.000238,40,linear,"{'C': 40, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
17,0.006453,0.004090,0.001329,0.000321,40,poly,"{'C': 40, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,13
18,0.001731,0.000420,0.001284,0.000301,40,rbf,"{'C': 40, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,9
19,0.002207,0.000762,0.001503,0.000495,40,sigmoid,"{'C': 40, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,16

In [29]:
result[["param_C","param_kernel","mean_test_score"]].sort_values(by="mean_test_score",ascending=False)

    param_C param_kernel  mean_test_score
0         1       linear         0.980000
2         1          rbf         0.980000
6        10          rbf         0.980000
4        10       linear         0.973333
10       20          rbf         0.966667
5        10         poly         0.966667
8        20       linear         0.966667
1         1         poly         0.966667
12       30       linear         0.960000
14       30          rbf         0.960000
16       40       linear         0.960000
18       40          rbf         0.960000
9        20         poly         0.953333
13       30         poly         0.953333
17       40         poly         0.953333
3         1      sigmoid         0.093333
7        10      sigmoid         0.093333
11       20      sigmoid         0.093333
15       30      sigmoid         0.093333
19       40      sigmoid         0.093333