In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [12]:
df=pd.read_csv("train.txt" ,sep=';' ,header=None,names=["text","Emotion"])

In [13]:
df.head()

                                                text  Emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [14]:
df.isnull().sum()

text       0
Emotion    0
dtype: int64

In [15]:
unique_emotions=df['Emotion'].unique()
Emotion_numbers={}
i=0
for emotion in unique_emotions:
    Emotion_numbers[emotion]=i
    i+=1

df['Emotion']=df['Emotion'].map(Emotion_numbers)

In [16]:
df

                                                    text  Emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [17]:
df["text"]=df["text"].apply(lambda x:x.lower())

In [18]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans("","",string.punctuation))

In [19]:
df["text"]=df["text"].apply(remove_punctuation)

In [20]:
def remove_numbers(text):
    new=""
    for i in text:
        if not i.isdigit():
            new+=i
    return new

df["text"]=df["text"].apply(remove_numbers)

In [21]:
def remove_emojis(text):
    new=""
    for i in text:
        if i.isascii():
            new+=i
    return new
df["text"]=df["text"].apply(remove_emojis)

In [22]:
#have to use nltk library to remove stopwords
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download("stopwords")
nltk.download("punkt_tab")
nltk.download("punkt")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mansi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mansi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mansi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [23]:
stop_words=set(stopwords.words("english"))

In [24]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [25]:
def remove_stopwords(text):
    word=word_tokenize(text)
    cleaned=[]
    for i in word:
        if i not in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)

In [26]:
df["text"]=df["text"].apply(remove_stopwords)

In [27]:
df.loc[1]["text"]

'go feeling hopeless damned hopeful around someone cares awake'

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df["text"], df["Emotion"], test_size=0.33, random_state=42)

In [33]:
df.shape

(16000, 2)

In [31]:
X_train

8917     feeling quite pleased fact one coupon use grocery
9453               stressed finally come end feel relieved
2829     feel blessed know immense family supporters co...
9681                       didnt feel like missed anything
12246            feel listless unable imagine ever working
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 10720, dtype: object

In [32]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
12538    feel really ought assert way smiles pleasant b...
6536     even sure formulate thoughts since put feeling...
13806         really feel quite honoured represent country
7724     ive feeling little overwhelmed whole thing lat...
5121     wanting write secret life live one handful peo...
Name: text, Length: 5280, dtype: object

In [35]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer


bow=CountVectorizer(ngram_range=(1,3))

bow=vectorizer.fit_transform(X_train)

AttributeError: 'Series' object has no attribute 'toarray'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents=[
    "I love pizza"
    "pizza is best",
    "i love pasta",
    "pasta is tasty"
]
vectorizer=TfidfVectorizer(ngram_range=(1,3))

X=vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['best' 'is' 'is best' 'is tasty' 'love' 'love pasta' 'love pizzapizza'
 'love pizzapizza is' 'pasta' 'pasta is' 'pasta is tasty' 'pizzapizza'
 'pizzapizza is' 'pizzapizza is best' 'tasty']
[[0.35013871 0.26628951 0.35013871 0.         0.26628951 0.
  0.35013871 0.35013871 0.         0.         0.         0.35013871
  0.35013871 0.35013871 0.        ]
 [0.         0.         0.         0.         0.51785612 0.68091856
  0.         0.         0.51785612 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.3349067  0.         0.44036207 0.         0.
  0.         0.         0.3349067  0.44036207 0.44036207 0.
  0.         0.         0.44036207]]