In [2]:
import numpy as np
import pandas as pd

In [3]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [4]:

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [5]:
df.head()

   soil_moisture  temperature_c  sunlight_hours  needs_water
0           0.10             34               9            1
1           0.15             30               8            1
2           0.20             26               7            1
3           0.25             22               4            0
4           0.40             28               8            0

In [6]:
X = df[["soil_moisture", "temperature_c", "sunlight_hours"]]
y=df["needs_water"]

In [7]:
X_min=X.min()
X_max=X.max()
X_scaled=(X-X_min)/(X_max-X_min+1e-8)

In [8]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.33, random_state=42)

In [10]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])

In [11]:
model.compile(optimizer="sgd",loss="binary_crossentropy", metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [12]:
history= model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=len(X_train),verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 801ms/step - accuracy: 0.2000 - loss: 0.7301 - val_accuracy: 0.1667 - val_loss: 0.7446
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.1000 - loss: 0.7297 - val_accuracy: 0.1667 - val_loss: 0.7447
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.1000 - loss: 0.7292 - val_accuracy: 0.1667 - val_loss: 0.7449
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.1000 - loss: 0.7288 - val_accuracy: 0.1667 - val_loss: 0.7450
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.1000 - loss: 0.7284 - val_accuracy: 0.1667 - val_loss: 0.7451
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.1000 - loss: 0.7280 - val_accuracy: 0.1667 - val_loss: 0.7453
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.0000e+00 - loss: 0.7276 - val_accuracy: 0.1667 - val_loss: 0.7454
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.0000e+00 - loss: 0.7271 - val_accuracy: 0.1667 - val_loss: 0.7455
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.0000e+00 - loss: 0.7267 - val_accuracy: 0.1667 - val_loss: 0.7457
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.0000e+00 - loss: 0.7263 - val_accuracy: 0.1667 - val_loss: 0.7458
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.1000 - loss: 0.7259 - val_accuracy: 0.1667 - val_loss: 0.7459
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.1000 - loss: 0.7256 - val_accuracy: 0.1667 - val_loss: 0.7461
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.1000 - loss: 0.7252 - val_accuracy: 0.0000e+00 - val_loss: 0.7462
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.1000 - loss: 0.7248 - val_accuracy: 0.0000e+00 - val_loss: 0.7463
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.1000 - loss: 0.7244 - val_accuracy: 0.0000e+00 - val_loss: 0.7465
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.1000 - loss: 0.7240 - val_accuracy: 0.0000e+00 - val_loss: 0.7466
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.1000 - loss: 0.7236 - val_accuracy: 0.0000e+00 - val_loss: 0.7468
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.1000 - loss: 0.7233 - val_accuracy: 0.0000e+00 - val_loss: 0.7469
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.1000 - loss: 0.7229 - val_accuracy: 0.0000e+00 - val_loss: 0.7470
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.1000 - loss: 0.7225 - val_accuracy: 0.0000e+00 - val_loss: 0.7472
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - accuracy: 0.1000 - loss: 0.7222 - val_accuracy: 0.0000e+00 - val_loss: 0.7473
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.1000 - loss: 0.7218 - val_accuracy: 0.0000e+00 - val_loss: 0.7474
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.1000 - loss: 0.7215 - val_accuracy: 0.0000e+00 - val_loss: 0.7476
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.1000 - loss: 0.7211 - val_accuracy: 0.0000e+00 - val_loss: 0.7477
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.1000 - loss: 0.7208 - val_accuracy: 0.0000e+00 - val_loss: 0.7478
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.1000 - loss: 0.7204 - val_accuracy: 0.0000e+00 - val_loss: 0.7480
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.1000 - loss: 0.7201 - val_accuracy: 0.0000e+00 - val_loss: 0.7481
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.1000 - loss: 0.7198 - val_accuracy: 0.0000e+00 - val_loss: 0.7482
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.1000 - loss: 0.7194 - val_accuracy: 0.0000e+00 - val_loss: 0.7484
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.1000 - loss: 0.7191 - val_accuracy: 0.0000e+00 - val_loss: 0.7485
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.2000 - loss: 0.7188 - val_accuracy: 0.0000e+00 - val_loss: 0.7486
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.2000 - loss: 0.7185 - val_accuracy: 0.0000e+00 - val_loss: 0.7487
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.2000 - loss: 0.7181 - val_accuracy: 0.0000e+00 - val_loss: 0.7489
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.2000 - loss: 0.7178 - val_accuracy: 0.0000e+00 - val_loss: 0.7490
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.2000 - loss: 0.7175 - val_accuracy: 0.0000e+00 - val_loss: 0.7491
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.2000 - loss: 0.7172 - val_accuracy: 0.0000e+00 - val_loss: 0.7493
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.2000 - loss: 0.7169 - val_accuracy: 0.0000e+00 - val_loss: 0.7494
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.3000 - loss: 0.7166 - val_accuracy: 0.0000e+00 - val_loss: 0.7495
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.3000 - loss: 0.7163 - val_accuracy: 0.0000e+00 - val_loss: 0.7497
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.3000 - loss: 0.7160 - val_accuracy: 0.0000e+00 - val_loss: 0.7498
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.3000 - loss: 0.7157 - val_accuracy: 0.0000e+00 - val_loss: 0.7499
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.3000 - loss: 0.7154 - val_accuracy: 0.0000e+00 - val_loss: 0.7500
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.3000 - loss: 0.7151 - val_accuracy: 0.0000e+00 - val_loss: 0.7502
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.3000 - loss: 0.7148 - val_accuracy: 0.0000e+00 - val_loss: 0.7503
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.3000 - loss: 0.7145 - val_accuracy: 0.0000e+00 - val_loss: 0.7504
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3000 - loss: 0.7142 - val_accuracy: 0.0000e+00 - val_loss: 0.7505
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.3000 - loss: 0.7139 - val_accuracy: 0.0000e+00 - val_loss: 0.7506
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.3000 - loss: 0.7137 - val_accuracy: 0.0000e+00 - val_loss: 0.7508
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.3000 - loss: 0.7134 - val_accuracy: 0.0000e+00 - val_loss: 0.7509
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.3000 - loss: 0.7131 - val_accuracy: 0.0000e+00 - val_loss: 0.7510
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.3000 - loss: 0.7129 - val_accuracy: 0.1667 - val_loss: 0.7511
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.3000 - loss: 0.7126 - val_accuracy: 0.1667 - val_loss: 0.7513
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.3000 - loss: 0.7123 - val_accuracy: 0.1667 - val_loss: 0.7514
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.3000 - loss: 0.7121 - val_accuracy: 0.1667 - val_loss: 0.7515
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.3000 - loss: 0.7118 - val_accuracy: 0.1667 - val_loss: 0.7516
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.3000 - loss: 0.7115 - val_accuracy: 0.1667 - val_loss: 0.7517
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - accuracy: 0.3000 - loss: 0.7113 - val_accuracy: 0.1667 - val_loss: 0.7518
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.3000 - loss: 0.7110 - val_accuracy: 0.1667 - val_loss: 0.7520
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.4000 - loss: 0.7108 - val_accuracy: 0.1667 - val_loss: 0.7521
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.4000 - loss: 0.7105 - val_accuracy: 0.1667 - val_loss: 0.7522
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.4000 - loss: 0.7103 - val_accuracy: 0.1667 - val_loss: 0.7523
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.4000 - loss: 0.7100 - val_accuracy: 0.1667 - val_loss: 0.7524
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.4000 - loss: 0.7098 - val_accuracy: 0.1667 - val_loss: 0.7525
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.4000 - loss: 0.7095 - val_accuracy: 0.1667 - val_loss: 0.7526
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.4000 - loss: 0.7093 - val_accuracy: 0.1667 - val_loss: 0.7527
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 0.7090 - val_accuracy: 0.1667 - val_loss: 0.7529
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5000 - loss: 0.7088 - val_accuracy: 0.1667 - val_loss: 0.7530
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.7086 - val_accuracy: 0.1667 - val_loss: 0.7531
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.5000 - loss: 0.7083 - val_accuracy: 0.1667 - val_loss: 0.7532
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - accuracy: 0.5000 - loss: 0.7081 - val_accuracy: 0.1667 - val_loss: 0.7533
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 362ms/step - accuracy: 0.5000 - loss: 0.7079 - val_accuracy: 0.1667 - val_loss: 0.7534
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - accuracy: 0.5000 - loss: 0.7077 - val_accuracy: 0.1667 - val_loss: 0.7535
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5000 - loss: 0.7074 - val_accuracy: 0.1667 - val_loss: 0.7536
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5000 - loss: 0.7072 - val_accuracy: 0.1667 - val_loss: 0.7537
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5000 - loss: 0.7070 - val_accuracy: 0.1667 - val_loss: 0.7538
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5000 - loss: 0.7068 - val_accuracy: 0.1667 - val_loss: 0.7539
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.6000 - loss: 0.7065 - val_accuracy: 0.1667 - val_loss: 0.7540
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6000 - loss: 0.7063 - val_accuracy: 0.1667 - val_loss: 0.7541
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6000 - loss: 0.7061 - val_accuracy: 0.1667 - val_loss: 0.7542
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.6000 - loss: 0.7059 - val_accuracy: 0.1667 - val_loss: 0.7543
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6000 - loss: 0.7057 - val_accuracy: 0.1667 - val_loss: 0.7544
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6000 - loss: 0.7055 - val_accuracy: 0.1667 - val_loss: 0.7545
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6000 - loss: 0.7053 - val_accuracy: 0.1667 - val_loss: 0.7546
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6000 - loss: 0.7050 - val_accuracy: 0.1667 - val_loss: 0.7547
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6000 - loss: 0.7048 - val_accuracy: 0.1667 - val_loss: 0.7548
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.6000 - loss: 0.7046 - val_accuracy: 0.1667 - val_loss: 0.7549
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6000 - loss: 0.7044 - val_accuracy: 0.1667 - val_loss: 0.7550
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6000 - loss: 0.7042 - val_accuracy: 0.1667 - val_loss: 0.7551
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6000 - loss: 0.7040 - val_accuracy: 0.1667 - val_loss: 0.7552
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6000 - loss: 0.7038 - val_accuracy: 0.1667 - val_loss: 0.7553
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6000 - loss: 0.7036 - val_accuracy: 0.1667 - val_loss: 0.7554
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6000 - loss: 0.7034 - val_accuracy: 0.1667 - val_loss: 0.7555
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6000 - loss: 0.7032 - val_accuracy: 0.1667 - val_loss: 0.7556
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6000 - loss: 0.7031 - val_accuracy: 0.1667 - val_loss: 0.7557
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6000 - loss: 0.7029 - val_accuracy: 0.1667 - val_loss: 0.7558
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 0.6000 - loss: 0.7027 - val_accuracy: 0.1667 - val_loss: 0.7559
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6000 - loss: 0.7025 - val_accuracy: 0.3333 - val_loss: 0.7559
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6000 - loss: 0.7023 - val_accuracy: 0.3333 - val_loss: 0.7560
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6000 - loss: 0.7021 - val_accuracy: 0.3333 - val_loss: 0.7561
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6000 - loss: 0.7019 - val_accuracy: 0.3333 - val_loss: 0.7562

In [13]:
from tensorflow.keras import optimizers

In [14]:
opt=optimizers.SGD(learning_rate=0.01, momentum=0.9)